### ISSUE TITLE
Generated LLVM is inefficient

### ISSUE THREAD

**Issue by romix** [dibyendumajumdar/ravi#32] opened 2015-04-26 01:51 UTC
When I look at the dumped LLVM IR, it looks pretty inefficient.

Let me try to explain what I mean:

One of the main reasons for it seems to be the fact that Ravi currently very closely models how LuaVM works with a stack. As a result, Ravi JIT always loads/stores operands of any Opcode to from/to memory, which prohibits many LLVM optimizations. While this is required upon entering a JITted function or leaving it (e.g. calling into a non-JITted code or returning), I'm not sure it is required inside the function being JITted. 

Overall, I think it is important to closely model LuaVM stack only when there is a chance it is being "observed" from outside of a JITted function and the stack is expected to be exactly as if it was prepared by LuaVM. 

But if you have a temporary value or a local variable which is not "observable" from outside, you are free to work with it without mapping it to a LuaVM stack. You can most likely simply model it as an "alloca" (of a TValue?) in LLVM IR and perform operations directly on it.

Eventually, you may even try to map all incoming LuaVM values to local LLVM "alloca" upon entering a function and store them back to the LuaVM stack upon leaving a function.

IMHO, keeping values in LLVM IR %-values would allow LLVM to perform common-subexpression-elimination, hoisting of values out of loops, load-store optimizations, copy forwarding and much more.

May be my view is rather naive and I miss an obvious reason why this cannot be done and one should always closely model the LuaVM stack inside the JITted function.

**Comment by romix** [comment] 2015-04-26 01:59
Some of the examples I used to see the LLVM IR inefficency:

```lua
local function test_sum(a, b)
  local count = 0
  count = a + b
  -- CSE should kick in here
  -- No need to reload a and b from stack as they are loaded already.
  -- No need for a check if a and b are integers, as this check was done already. 
  count = a + b 
  return count
end
```

or 

```lua
local function test_loop()
  -- count is local and there is no need to model it via LuaVM stack.
  -- it could be used an LLVM "alloca" %-value
  local count = 0
  -- i is also local and can be an LLVM %-value.  
  -- The whole loop should actually JITted into something similar to a code that would be produced 
  -- for an equivalent C-loop. 
  -- There should be no type checks inside a loop, because the type of count is known from above.
  -- The whole body should be virtually just one "inc" instruction.
  for i=0, 1234567890 do
    count = count + 1
  end
  -- OK. Copy the result to LuaVM stack.
  return count
end
```

**Comment by dibyendumajumdar** [comment] 2015-04-26 02:40
Hi - more optimizations are possible certainly. The use of the Lua stack is closely coupled with how the garbage collector works. For primitive types, you are correct that as long as the value is not being observed it could avoid using the Lua stack. I do not know how much effort it will be though to implement some of these optimizations. Another way of optimizing numeric values is to use NaN tagging approach. 

I considered type inference at one point but found that it would break compatibility with Lua.  

Have you looked at the IR when static typing is used? In the benchmarks this improves things significantly in many cases. 

Re the for loop the problem is that Lua maintains an extra variable in addition to the internal loop variable. This variable can be eliminated only if it is not being written to and is not converted into an up-value for a closure.

**Comment by romix** [comment] 2015-04-26 02:56
> The use of the Lua stack is closely coupled with how the garbage collector works.

I see. I'm still wondering though if more optimizations can be done for local variables inside functions, if you can prove/speculate that they are of primitive types (e.g. loop counters).

> Re the for loop the problem is that Lua maintains an extra variable in addition to the internal loop 
> variable. This variable can be eliminated only if it is not being written to and is not converted into an up-
> value for a closure.

But it is rather easy to analyze the emitted IR or Lua opcodes for a given function to check if a given variable is not written to and is not converted into an up-value for a closure, or?

**Comment by romix** [comment] 2015-04-26 03:03
I tried with a static typing, e.g. 

```lua
local function test_loop()
  local count: integer = 0
  local i:integer
  for i=0, 1234567890 do
    count = count + 1
  end
  return count
end
```

And the IR seems to be pretty inefficient even with the static type info. Yes, it knows it can use integer addition. But inside the loop it still goes via LuaVM stack for reading/writing the `count` and `i` values, which is not good.

**Comment by romix** [comment] 2015-04-26 03:13
Re the values of non-primitive types. I totally see that the fact they are allocated on heap makes it very dependent on the LuaVM GC and they way how it traverses the LuaVM stack. But if you can prove that a given variable does not ever escape the current scope, you probably can allocate it on stack by means of something like SROA in LLVM (scalar replacement of aggregates)?

**Comment by dibyendumajumdar** [comment] 2015-04-26 10:13
Are you using the latest version from Git or one of the builds? The latest version has slightly better code generation due to the fact that I was missing a DataLayout pass on the module.

If you let me know what platform you are trying this on I can create a new build.

**Comment by dibyendumajumdar** [comment] 2015-04-26 10:19
Values in Lua when dynamically typed are hard to analyse as they can invoke metamethods - so '+' may be a user defined function. I think a trace compiler like Luajit can wait until code executes to determine what the real types are and then optimize.

In Ravi, static typing is meant to give you this same benefit - as it tells the compiler that the values are primitive and cannot invoke metamethods. So in theory - with static typing - it is possible to check that the variable is completely local, is not being captured as an upvalue, etc. and then optimize code generation to use C stack rather than Lua stack. I guess I am new to this area so it will take me some time to get to the point where I can implement this.

I do implement this for the index variable in fornum loops. The loop index is an alloca - but within the loop I still set the Lua "external" variable as without proving that this is not being written to or escaping it is not possible to eliminate the write.

**Comment by dibyendumajumdar** [comment] 2015-04-26 10:29
I think the other issue is that I am currently JIT compiling Lua byte code - by this time the type information is lost. To really do this I would need to have a new Lua parser and code generator that preserves type information so that the compiler can optimize. (I am somewhat simplifying here but the gist is correct).

**Comment by romix** [comment] 2015-04-26 15:17
> I think a trace compiler like Luajit can wait until code executes to determine what the real types are and 
> then optimize.

I'm wondering if you cannot do something similar in the `auto` mode. I guess you intercept the calls of a function anyways. Can't you also record the types of passed parameters you've seen so far? If you see that a certain parameter was of a primitive numeric type, you could generate an "optimized" specialization of a function, which makes use of it.

For local variables, like counters, you could probably derive the type (i.e. that it is a primitive numeric type) from its initialzation and traversing all its uses in many cases? If the initialization and all uses seem to set/preserve the primitive numeric type, you know that it is "integer" or "double" during its lifetime.

Even if you still go through LuaVM stack, you could probably check that a certain stack slot is only read from, but never written to. In such a case, you could at least perform loads/typechecks on the value from this slot only once. This may help a lot in cases, where you refer to this slot multiple times inside the function body, in particular inside loops.

> I do implement this for the index variable in fornum loops. The loop index is an alloca - but within the 
> loop I still set the Lua "external" variable as without proving that this is not being written to or escaping 
> it is not possible to eliminate the write.

Is it difficult to prove it? I guess it only requires a pass over the bytecode of a function to check if a given "external" variable e.g. is written to or is escaping.

**Comment by romix** [comment] 2015-04-26 15:43
> I do implement this for the index variable in fornum loops. The loop index is an alloca - but within the 
> loop I still set the Lua "external" variable as without proving that this is not being written to or escaping 
> it is not possible to eliminate the write.

Yes, I used the latest trunk and built my binaries on OS X. Indeed, the loop index is an alloca, but you still update the "external" variable on each iteration.

**Comment by dibyendumajumdar** [comment] 2015-04-26 16:55
Since the JIT works at the level of a function, specializing the function for argument types etc is equivalent to treating the function as a template - I think Julia does this. 

On the other hand once I implement static typing for parameters then this knowledge will be available to the compiler and there won't be a need to specialize the function for argument types.

I agree that lot more optimization is possible and there are several ways of achieving the end result. 

BTW the Lua local variables have lexical scope and the way the compiler generates the bytecode means that the same variable slot (position in stack) can hold different values at different times. This is complicated further by the fact that you can define functions inside functions and the embedded function can access the variables of the outer function.

**Comment by dibyendumajumdar** [comment] 2016-08-23 10:59
Closing as no specific approach / design to persue here.

**Closed by dibyendumajumdar** 2016-08-23 10:59 UTC
